@claims_sg_auditor_duke.sql
@claims_sg_dev_owen.sql
@claims_sg_finance_stafford.sql
@claims_sg_hr_xerxes.sql
@cred_sg_auditor_duke.sql
@cred_sg_dev_owen.sql
@cred_sg_finance_stafford.sql
@cred_sg_hr_xerxes.sql
@esd_sg_auditor_duke.sql
@esd_sg_dev_owen.sql
@esd_sg_finance_stafford.sql
@esd_sg_hr_xerxes.sql
@eval_blaze_mngr.sql
@eval_cameron_simple.sql
@eval_sg_hr_xerxes.sql
@jobs_sg_hr_xerxes.sql
@jobs_sg_dev_owen.sql
@leaves_sg_hr_xerxes.sql
@leaves_sg_dev_owen.sql
@leaves_sg_finance_stafford.sql
@payslips_sg_auditor_duke.sql
@payslips_sg_dev_owen.sql
@payslips_sg_finance_stafford.sql
@payslips_sg_hr_xerxes.sql
