CREATE OR REPLACE CONTEXT EMPLOYEE_MGMT USING CS5322.EMPLOYEE_VPD;

CREATE OR REPLACE PACKAGE EMPLOYEE_VPD AS
    PROCEDURE set_context;
END;


CREATE OR REPLACE PACKAGE BODY EMPLOYEE_VPD IS
    PROCEDURE set_context IS
        v_ouser VARCHAR2(30);
        v_id NUMBER;
    BEGIN
        DBMS_SESSION.set_context('EMPLOYEE_MGMT', 'SETUP','TRUE');
        v_ouser := SYS_CONTEXT('USERENV','SESSION_USER');
        
        BEGIN
            SELECT id
            INTO v_id
            FROM EMPLOYEES
            WHERE SLUG = v_ouser;
            
            DBMS_SESSION.set_context('EMPLOYEE_MGMT', 'USER_ID', v_id);
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                DBMS_SESSION.set_context('EMPLOYEE_MGMT' , 'USER_ID', 0);
        END;
        
        DBMS_SESSION.set_context('EMPLOYEE_MGMT', 'SETUP', 'FALSE');
        END set_context;
END EMPLOYEE_VPD;

GRANT EXECUTE ON EMPLOYEE_VPD TO PUBLIC;
CREATE OR REPLACE PUBLIC SYNONYM EMPLOYEE_VPD FOR CS5322.EMPLOYEE_VPD;
CREATE OR REPLACE TRIGGER SET_EMPLOYEE_MGMT_CONTEXT 
AFTER LOGON ON DATABASE 
BEGIN
  EMPLOYEE_VPD.set_context;
END;